name: Prettier Code Formatter
on:
  pull_request:
    branches: [main]
  push:
    branches: [main]

jobs:
  prettier:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Código
        uses: actions/checkout@v4

      - name: Instalar Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Instalar Dependencias
        run: npm ci

      - name: Verificar Formato con Prettier
        run: npx prettier --check .
